import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/layout/Navbar";
import { Geist } from "next/font/google";
import { cn } from "@/lib/utils";

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

const arabicDin = localFont({
  src: [
    {
      path: "../public/fonts/Arabic/URWDINArabicRegular.ttf",
      weight: "300",
      style: "normal",
    },
  ],
  variable: "--font-arabic-din",
  display: "swap",
});

// const englishDin = localFont({
//   src: [
//     {
//       path: "../../public/fonts/English/EnglishDinLight.ttf",
//       weight: "300",
//       style: "normal",
//     },
//   ],
//   variable: "--font-english-din",
//   display: "swap",
// });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="ar" className={cn("h-full", "antialiased", arabicDin.variable, "font-sans", geist.variable)}>
      <body className="min-h-full flex flex-col bg-home-background">
        <Navbar />
        <main>{children}</main>
      </body>
    </html>
  );
}
