export type Category = {
  id: string;
  name: string;         
  nameEn: string;       
  slug: string;
  image?: string;
};


export const categories: Category[] = [
  { id: "c1", name: "تاجير معدات",  nameEn: "Equipments rent",   slug: "rental",  image: "/images/category-rental.png" },
  { id: "c2", name: "معدات انشاء",       nameEn: "Construction Equipments",       slug: "construction",            image: "/images/category-construction.png" },
  { id: "c3", name: "لوازم الحفلات", nameEn: "Party supplies", slug: "party",            image: "/images/category-party.png" },
  { id: "c4", name: "معدات تصوير", nameEn: "Photography Equipments",     slug: "camera",         image: "/images/category-camera.png" },
  { id: "c5", name: "مقتنيات شخصية",       nameEn: "Personal belongings",        slug: "personal",      image: "/images/category-personal.png" },
  { id: "c6", name: "الكترونيات",       nameEn: "Electronics",          slug: "electronics",        image: "/images/category-electronics.png" },
  { id: "c7", name: "اخرى",       nameEn: "Other",       slug: "other",      image: "/images/category-other.png" },
];


import { Product } from "@/types/home/types";

export const products: Product[] = [
  {
    id: "p1",
    name: "طقم كاسات كريستال RCR Timeless — إيطالي الصنع",
    nameEn: "RCR Timeless Crystal Glass Set — Made in Italy",
    slug: "rcr-timeless-crystal-glass-set",
    category: "party",
    categoryName: "لوازم الحفلات",
    categoryNameEn: "Party supplies",
    price: 210,
    oldPrice: 280,
    discount: 25,
    rating: 4.7,
    reviews: 132,
    location: "الرياض",
    image: "/images/products/p1.jpg",
    images: ["/images/products/p1.jpg", "/images/products/p1-2.jpg"],
    badge: "sale",
    inStock: true,
    description: "طقم كاسات كريستال فاخر من RCR الإيطالية، مثالي للمناسبات والحفلات.",
  },
  {
    id: "p2",
    name: "سماعات لاسلكية Sony WH-1000XM5",
    nameEn: "Sony WH-1000XM5 Wireless Headphones",
    slug: "sony-wh-1000xm5",
    category: "electronics",
    categoryName: "الكترونيات",
    categoryNameEn: "Electronics",
    price: 1499,
    oldPrice: 1799,
    discount: 17,
    rating: 4.9,
    reviews: 842,
    location: "الرياض",
    image: "/images/products/p2.jpg",
    images: ["/images/products/p2.jpg"],
    badge: "best-seller",
    inStock: true,
    description: "أفضل سماعات إلغاء الضوضاء مع جودة صوت استثنائية وبطارية تدوم 30 ساعة.",
  },
  {
    id: "p3",
    name: "آيفون 15 برو ماكس 256 جيجا",
    nameEn: "iPhone 15 Pro Max 256GB",
    slug: "iphone-15-pro-max-256",
    category: "electronics",
    categoryName: "الكترونيات",
    categoryNameEn: "Electronics",
    price: 5199,
    rating: 4.8,
    reviews: 2134,
    location: "جدة",
    image: "/images/products/p3.jpg",
    images: ["/images/products/p3.jpg"],
    badge: "new",
    inStock: true,
    description: "أحدث إصدار من آيفون مع شريحة A17 Pro وكاميرا احترافية.",
  },
  {
    id: "p4",
    name: "ساعة سامسونج Galaxy Watch 6",
    nameEn: "Samsung Galaxy Watch 6",
    slug: "samsung-galaxy-watch-6",
    category: "electronics",
    categoryName: "الكترونيات",
    categoryNameEn: "Electronics",
    price: 1099,
    oldPrice: 1299,
    discount: 15,
    rating: 4.6,
    reviews: 421,
    location: "الدمام",
    image: "/images/products/p4.jpg",
    images: ["/images/products/p4.jpg"],
    badge: "sale",
    inStock: true,
    description: "ساعة ذكية بتصميم أنيق وتتبع صحي متقدم.",
  },
  {
    id: "p5",
    name: "لابتوب MacBook Air M3",
    nameEn: "MacBook Air M3",
    slug: "macbook-air-m3",
    category: "electronics",
    categoryName: "الكترونيات",
    categoryNameEn: "Electronics",
    price: 4499,
    rating: 4.9,
    reviews: 689,
    location: "الرياض",
    image: "/images/products/p5.jpg",
    images: ["/images/products/p5.jpg"],
    badge: "new",
    inStock: true,
    description: "خفيف، سريع، وبطارية تدوم طوال اليوم مع شريحة M3.",
  },
  {
    id: "p6",
    name: "قميص رجالي كلاسيك قطن",
    nameEn: "Men's Classic Cotton Shirt",
    slug: "mens-classic-cotton-shirt",
    category: "personal",
    categoryName: "مقتنيات شخصية",
    categoryNameEn: "Personal belongings",
    price: 149,
    oldPrice: 199,
    discount: 25,
    rating: 4.4,
    reviews: 218,
    location: "الرياض",
    image: "/images/products/p6.jpg",
    images: ["/images/products/p6.jpg"],
    badge: "sale",
    inStock: true,
    description: "قميص قطن 100% بقصة عصرية، متوفر بعدة ألوان.",
  },
  {
    id: "p7",
    name: "عباية نسائية مطرزة",
    nameEn: "Women's Embroidered Abaya",
    slug: "womens-embroidered-abaya",
    category: "personal",
    categoryName: "مقتنيات شخصية",
    categoryNameEn: "Personal belongings",
    price: 349,
    rating: 4.8,
    reviews: 176,
    location: "مكة",
    image: "/images/products/p7.jpg",
    images: ["/images/products/p7.jpg"],
    badge: "best-seller",
    inStock: true,
    description: "عباية أنيقة بتطريز يدوي، مثالية للمناسبات.",
  },
  {
    id: "p8",
    name: "حذاء رياضي Nike Air Max",
    nameEn: "Nike Air Max Sneakers",
    slug: "nike-air-max-sneakers",
    category: "personal",
    categoryName: "مقتنيات شخصية",
    categoryNameEn: "Personal belongings",
    price: 599,
    oldPrice: 749,
    discount: 20,
    rating: 4.7,
    reviews: 534,
    location: "جدة",
    image: "/images/products/p8.jpg",
    images: ["/images/products/p8.jpg"],
    badge: "sale",
    inStock: true,
    description: "حذاء رياضي مريح بتصميم عصري وتقنية Air Max.",
  },
  {
    id: "p9",
    name: "حقيبة يد جلد طبيعي",
    nameEn: "Genuine Leather Handbag",
    slug: "genuine-leather-handbag",
    category: "personal",
    categoryName: "مقتنيات شخصية",
    categoryNameEn: "Personal belongings",
    price: 459,
    rating: 4.6,
    reviews: 92,
    location: "الرياض",
    image: "/images/products/p9.jpg",
    images: ["/images/products/p9.jpg"],
    inStock: true,
    description: "حقيبة يد أنيقة من الجلد الطبيعي، متوفرة بعدة ألوان.",
  },
  {
    id: "p10",
    name: "طقم أواني طهي 10 قطع",
    nameEn: "10-Piece Cookware Set",
    slug: "10-piece-cookware-set",
    category: "other",
    categoryName: "اخرى",
    categoryNameEn: "Other",
    price: 399,
    oldPrice: 549,
    discount: 27,
    rating: 4.5,
    reviews: 311,
    location: "الرياض",
    image: "/images/products/p10.jpg",
    images: ["/images/products/p10.jpg"],
    badge: "sale",
    inStock: true,
    description: "طقم أواني طهي غير لاصق، مناسب لجميع أنواع المواقد.",
  },
  {
    id: "p11",
    name: "ماكينة قهوة نسبريسو",
    nameEn: "Nespresso Coffee Machine",
    slug: "nespresso-coffee-machine",
    category: "other",
    categoryName: "اخرى",
    categoryNameEn: "Other",
    price: 899,
    rating: 4.8,
    reviews: 654,
    location: "الدمام",
    image: "/images/products/p11.jpg",
    images: ["/images/products/p11.jpg"],
    badge: "best-seller",
    inStock: true,
    description: "ماكينة قهوة أنيقة وسهلة الاستخدام، مثالية للمنزل والمكتب.",
  },
  {
    id: "p12",
    name: "مفرش سرير قطني 4 قطع",
    nameEn: "4-Piece Cotton Bed Sheet Set",
    slug: "cotton-bed-sheet-set",
    category: "other",
    categoryName: "اخرى",
    categoryNameEn: "Other",
    price: 279,
    oldPrice: 349,
    discount: 20,
    rating: 4.3,
    reviews: 147,
    location: "جدة",
    image: "/images/products/p12.jpg",
    images: ["/images/products/p12.jpg"],
    badge: "sale",
    inStock: true,
    description: "مفرش سرير قطني ناعم، متوفر بمقاسات وألوان متعددة.",
  },
  {
    id: "p13",
    name: "عطر شانيل رقم 5",
    nameEn: "Chanel No. 5 Perfume",
    slug: "chanel-no-5-perfume",
    category: "personal",
    categoryName: "مقتنيات شخصية",
    categoryNameEn: "Personal belongings",
    price: 799,
    rating: 4.9,
    reviews: 982,
    location: "الرياض",
    image: "/images/products/p13.jpg",
    images: ["/images/products/p13.jpg"],
    badge: "best-seller",
    inStock: true,
    description: "عطر أيقوني للنساء، برائحة زهرية أنيقة تدوم طويلاً.",
  },
  {
    id: "p14",
    name: "كريم مرطب للوجه La Roche-Posay",
    nameEn: "La Roche-Posay Face Moisturizer",
    slug: "la-roche-posay-moisturizer",
    category: "personal",
    categoryName: "مقتنيات شخصية",
    categoryNameEn: "Personal belongings",
    price: 189,
    oldPrice: 229,
    discount: 17,
    rating: 4.7,
    reviews: 423,
    location: "الرياض",
    image: "/images/products/p14.jpg",
    images: ["/images/products/p14.jpg"],
    badge: "sale",
    inStock: true,
    description: "كريم مرطب مناسب للبشرة الحساسة، خالٍ من العطور.",
  },
  {
    id: "p15",
    name: "طقم فرش مكياج 12 قطعة",
    nameEn: "12-Piece Makeup Brush Set",
    slug: "12-piece-makeup-brush-set",
    category: "personal",
    categoryName: "مقتنيات شخصية",
    categoryNameEn: "Personal belongings",
    price: 129,
    rating: 4.5,
    reviews: 267,
    location: "جدة",
    image: "/images/products/p15.jpg",
    images: ["/images/products/p15.jpg"],
    inStock: true,
    description: "طقم فرش مكياج احترافي، مناسب لجميع أنواع المكياج.",
  },
  {
    id: "p16",
    name: "دمبل قابل للتعديل 20 كجم",
    nameEn: "Adjustable Dumbbell 20kg",
    slug: "adjustable-dumbbell-20kg",
    category: "other",
    categoryName: "اخرى",
    categoryNameEn: "Other",
    price: 449,
    oldPrice: 599,
    discount: 25,
    rating: 4.6,
    reviews: 189,
    location: "الرياض",
    image: "/images/products/p16.jpg",
    images: ["/images/products/p16.jpg"],
    badge: "sale",
    inStock: true,
    description: "دمبل قابل للتعديل، مثالي للتمارين المنزلية.",
  },
  {
    id: "p17",
    name: "سجادة يوغا غير قابلة للانزلاق",
    nameEn: "Non-Slip Yoga Mat",
    slug: "non-slip-yoga-mat",
    category: "other",
    categoryName: "اخرى",
    categoryNameEn: "Other",
    price: 99,
    rating: 4.4,
    reviews: 312,
    location: "الدمام",
    image: "/images/products/p17.jpg",
    images: ["/images/products/p17.jpg"],
    inStock: true,
    description: "سجادة يوغا مريحة وغير قابلة للانزلاق، بسماكة 6 مم.",
  },
  {
    id: "p18",
    name: "مكعبات ليغو 500 قطعة",
    nameEn: "LEGO 500-Piece Set",
    slug: "lego-500-piece-set",
    category: "other",
    categoryName: "اخرى",
    categoryNameEn: "Other",
    price: 299,
    rating: 4.8,
    reviews: 456,
    location: "الرياض",
    image: "/images/products/p18.jpg",
    images: ["/images/products/p18.jpg"],
    badge: "best-seller",
    inStock: true,
    description: "مجموعة مكعبات ليغو إبداعية، مناسبة للأطفال من عمر 6 سنوات.",
  },
  {
    id: "p19",
    name: "لعبة تحكم عن بعد سيارة سباق",
    nameEn: "RC Racing Car",
    slug: "rc-racing-car",
    category: "other",
    categoryName: "اخرى",
    categoryNameEn: "Other",
    price: 199,
    oldPrice: 259,
    discount: 23,
    rating: 4.5,
    reviews: 178,
    location: "جدة",
    image: "/images/products/p19.jpg",
    images: ["/images/products/p19.jpg"],
    badge: "sale",
    inStock: true,
    description: "سيارة سباق بالتحكم عن بعد، سرعة عالية وبطارية قابلة للشحن.",
  },
];
